export default {
  light: {
    text: '#FFFFFF',
    mainBackground: '#FFFFFF',
    cardBackground: '#FDFDFD',
    customBtnBackground: '#7EF9FF',
    customBtnTitle: '#3D0C02',
    upcomingEventsBackground: '#F9F9EF',
    upcomingEventsActionBtn: '#F0F8FF',
    upcomingEventsMoreBtn: '#6F00FF',
    upcomingEventsTitle: '#3C3C3C',
    upcomingEventsDate: '#251D40',
    divider: '#251D40',
    icon: '#FFFFFF',
  },
  dark: {
    text: '#FFFFFF',
    mainBackground: '#1C1C1C',
    cardBackground: '#2C2C2C',
    customBtnBackground: '#234F65',
    customBtnTitle: '#E3DCC9',
    upcomingEventsBackground: '#1F1F1F',
    upcomingEventsActionBtn: '#0F0F0F',
    upcomingEventsMoreBtn: '#B439FF',
    upcomingEventsTitle: '#EDEDED',
    upcomingEventsDate: '#B2A8CC',
    divider: '#B2A8CC',
    icon: '#FFFFFF',
  },
  customBtnBackground: '#7EF9FF',
  lightOld: {
    primary: '#f3f4f6',
    secondary: '#ffffff',
    tertiary: '#4b5563',
    accent: '#0891b2',
    tint: '#111827',
  },
  darkOld: {
    primary: '#1f2937',
    secondary: '#111827',
    tertiary: '#d1d5db',
    accent: '#0891b2',
    tint: '#f9fafb',
  },
  red: '#E66155',
  green: '#60C5A8',
  blue: 'skyblue',
  black: '#000000',
  white: '#FFFFFF',

  primary: '#f3f4f6',
  secondary: '#ffffff',
  tertiary: '#4b5563',
  accent: '#0891b2',
  tint: '#111827',
};
